Properly format IPv6 bind address strings
This fixes:
    Error: '::9443' is not a valid port number.

Introduce unit test skeleton for amphora agent.

Change-Id: Ic7aebf0674ba7036356bb3231c26fa309cd4c475