Fix duplicate object error messages
Fixed an issue where creation of duplicate listeners or members may have
not returned the correct error message to users.
The API would traceback with AttributeError: 'NoneType' object has no attribute 'to_dict'

Made adjustments to patch for Python 2 compatibility in Train.

 Conflicts:
	octavia/api/v2/controllers/member.py
	octavia/api/v2/controllers/listener.py

Story: 2009128
Task: 43045
Change-Id: Ibbccda5859c8c6129d43e0742b28b319b49ddd1f
(cherry picked from commit f166bb1481fb58acd7e7329ec394f43249001718)
(cherry picked from commit e69899824ce09b8eb72c294562fdae5ad7ad5c13)
(cherry picked from commit 5647db94c941f582bb8292599379a3693b470cbe)
(cherry picked from commit ca66aac3750d7e2ff005111ade5212a2092e25a8)
(cherry picked from commit a1e22d89a4852a28a3e60b31b4b293199daac0ab)