Fix functional tests under Python >= 3.6
Newer Python versions don't like passing a mock in to an os.path.join:

  TypeError: join() argument must be str or bytes, not 'MagicMock'

This patch also adds openstack-tox-functional-py36 to the gate queue.
Recent and major LTS distributions ship Python 3.6 or greater.

Change-Id: Ic71059da24e0d2c3f0ac3af5375906d8e8aa43f4
(cherry picked from commit b5dda3ce0570dbc888d77bfff9b13321eb33608c)