Fix compile_amphora_details when using UDP listeners
When requesting the amphora details of a LB that has a UDP listener, it
fails with an exception:

  AttributeError: 'KeepalivedLvs' object has no attribute
    'is_listener_running'

There's a typo in the _count_lvs_listener_processes function which calls
an inexisting method.

Conflicts:
	octavia/amphorae/backends/agent/api_server/amphora_info.py
	octavia/tests/unit/amphorae/backends/agent/api_server/test_amphora_info.py

Change-Id: Id81ac8dfdd969c7b250d231123d392eff4a86269
(cherry picked from commit 655fdf8c1b5786c3aa24c926dd95537a51a7c0cc)
(cherry picked from commit c44c831649f970d3259bad95d2d2213f9b8167f6)
(cherry picked from commit 5997304d878d63adf495b470993674f0e0fbcc9a)
(cherry picked from commit 2b2494d7c737843c759ca5aaeb8edf17eab05d01)
(cherry picked from commit c362bacfe1d123467d4a3a1b987c03bf14dbb37c)
(cherry picked from commit 9cb77a0b81e7dda1cb7e9240fc00c122dcdfc48b)