Fix duplicate object error messages
Fixed an issue where creation of duplicate listeners or members may have
not returned the correct error message to users.
The API would traceback with AttributeError: 'NoneType' object has no attribute 'to_dict'

Story: 2009128
Task: 43045
Change-Id: Ibbccda5859c8c6129d43e0742b28b319b49ddd1f
(cherry picked from commit f166bb1481fb58acd7e7329ec394f43249001718)
(cherry picked from commit e69899824ce09b8eb72c294562fdae5ad7ad5c13)