Fix create_server_group in compute noop
When using Noop+ACTIVE_STANDBY+anti_affinity, create_server_group
doesn't return a value but the caller (NovaServerGroupCreate.execute)
accesses to the id attribute of the returned value, it triggers an
AttributeError:

File "../worker/v2/tasks/compute_tasks.py", line 319, in execute
        "%s", server_group.id, loadbalancer_id)
AttributeError: 'NoneType' object has no attribute 'id'

This commit adds a fake object that is returned by the noop driver.

Change-Id: I579c1e7bd364b3c34e9a813f99c77d30753d288b
(cherry picked from commit 5fff5676d7bf87d6fda0421e0066ce1958c5db5e)
(cherry picked from commit 7a2c472ee4a498902f98ff5f30c9e2b26be8d236)